{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-officedown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/officedown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/officedown/officedown_{{ version }}.tar.gz
  sha256: 9cecfc3466e0606ac3d48c8ae66d581cf8f36294474bb0208bcb170c4518e3f3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-knitr
    - r-memoise
    - r-officer >=0.3.18
    - r-rlang
    - r-rmarkdown
    - r-rvg >=0.2.2
    - r-uuid
    - r-xml2
    - r-yaml
  run:
    - r-base
    - r-knitr
    - r-memoise
    - r-officer >=0.3.18
    - r-rlang
    - r-rmarkdown
    - r-rvg >=0.2.2
    - r-uuid
    - r-xml2
    - r-yaml

test:
  commands:
    - $R -e "library('officedown')"           # [not win]
    - "\"%R%\" -e \"library('officedown')\""  # [win]

about:
  home: https://davidgohel.github.io/officedown
  license: MIT
  summary: Allows production of 'Microsoft' corporate documents from 'R Markdown' by reusing formatting defined in 'Microsoft Word' documents. You can reuse table styles, list styles but also add column sections, landscape oriented pages. Table and image captions as well as cross-references are transformed into 'Microsoft
    Word' fields, allowing documents edition and merging without issue with references; the syntax conforms to the 'bookdown' cross-reference definition. Objects generated by the 'officer' package are also supported in the 'knitr' chunks. 'Microsoft PowerPoint' presentations also benefit from this as well as the ability
    to produce editable vector graphics in 'PowerPoint' and also to define placeholder where content is to be added.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - bsennblad
